// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGPj9Q-GyrEN7ciHwSUZg2xSWCtqOvwmI',
    appId: '1:746485811884:web:3f789c8fc868ca7b7f2d09',
    messagingSenderId: '746485811884',
    projectId: 'oilab-860c2',
    authDomain: 'oilab-860c2.firebaseapp.com',
    storageBucket: 'oilab-860c2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIYOfVJC0BolK8r4xNFeLouFGPeSuyX48',
    appId: '1:746485811884:android:13fb42dab58706807f2d09',
    messagingSenderId: '746485811884',
    projectId: 'oilab-860c2',
    storageBucket: 'oilab-860c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJoWRiPPUaG9JmIAeaB6FDXkXg3QRRW4Q',
    appId: '1:746485811884:ios:006a1e552b4cdea67f2d09',
    messagingSenderId: '746485811884',
    projectId: 'oilab-860c2',
    storageBucket: 'oilab-860c2.appspot.com',
    iosClientId: '746485811884-bg67gqc2fvfl8opqm8vi4mdh3uu642c5.apps.googleusercontent.com',
    iosBundleId: 'com.example.oilabTask',
  );
}
